Fixing missing configurations on pom.xml (#73)
* Add configuration to ignore plugin lifecycle management for some plugins
not supported by m2e Eclipse plugin.

* Fix NoClassDefFoundError of
org.jenkinsci.plugins.workflow.steps.SynchronousStepExecution class on
startup